GET http://localhost:3000/api HTTP/1.1

# 채팅방
### 채팅방 생성
POST http://localhost:3000/api/chat/room/create HTTP/1.1
Content-Type: application/json

{
  "roomName": "채팅방 이름 샘플1"
}

### 채팅방 입장
POST http://localhost:3000/api/chat/room/enter/648f0b2ba569dcbbce86d7f8 HTTP/1.1
Content-Type: application/json

{
  "memberName": "멤버 이름 샘플1"
}

# Scrum Dice
### 채팅방 생성
POST http://localhost:3000/api/scrum-dice/room/create HTTP/1.1
Content-Type: application/json

{
  "roomName": "scrum-dice 채팅방 이름 샘플1"
}

### 채팅방 입장
POST http://localhost:3000/api/scrum-dice/room/enter/648f0b13a569dcbbce86d7f6 HTTP/1.1
Content-Type: application/json

{
  "memberName": "scrum-dice 멤버 이름 샘플1"
}
